
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
env:
  - CXX=g++-4.8
cache:
  directories:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install: 'if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi'
install: 'rm -rf node_modules && npm install && npm install -g istanbul'
script: 'npm test'
after_script: 'npm install coveralls && cat coverage/lcov.info | ./node_modules/.bin/coveralls'
notifications:
  email: false
  slack:
    rooms:
      - sumanjs:gvauyHh80cuzpV5v8LlQOAcI#travis-ci
